services:
  - type: web
    name: parking-backend
    env: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/parkingbackend-0.0.1-SNAPSHOT.jar"
    plan: free
    region: oregon
