services:
  - type: web
    name: parking-backend
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: ""          # Not needed when using Dockerfile
    startCommand: ""           # Dockerfile handles it
    healthCheckPath: "/actuator/health"
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx512m"
